Models/CompanyModel.cs
namespace DotNetProject.Models;

public class CompanyModel
{ 
    public string? Name { get; set; }
    
}

Models/ErrorViewModel.cs
namespace DotNetProject.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;

namespace DotNetProject.Controllers;

public class CompanyController : Controller
{

    public IActionResult Index()
    {

        return View();
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DotNetProject.Models;

namespace DotNetProject.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/RandomNumberController.cs
using Microsoft.AspNetCore.Mvc;

namespace YourNamespace.Controllers
{
    public class RandomNumberController : Controller
    {
        public IActionResult Index()   
        {
            // Generate rundom number from 0 to 100
            Random random = new Random();
            int randomNumber = random.Next(101);

            ViewBag.RandomNumber = randomNumber;

            return View();
        }
    }
}

Views/Company/Index.cshtml
@model CompanyModel

@{
    ViewData["Title"] = "Cats Company Main Page";
}

<div class="text-center">
    <h1 class="display-4">Cats Company Main Page</h1>
    <p>this is a new page for laba number #1</p>


    <form class="text-center" method="post" asp-controller="Company" >

        <label asp-for="Name"></label>
        <input asp-for="Name" />

        <input type="submit" value="This is my name" />
        
    </form>

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Cat Main Page";
}

<div class="text-center">
    <h1 class="display-4">Cat page</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/RandomNumber/Index.cshtml
@{
    ViewData["Title"] = "Random number";
}

    <h1>Here you can generate random number from 0 to 100:</h1>
    <p id="randomNumberDisplay">Click the button to generate a random number.</p>
    <button id="generateButton">Generate random number</button>

    <script>
        document.getElementById("generateButton").addEventListener("click", function () {
            // Generate rundom number from 0 to 100
            var randomNumber = Math.floor(Math.random() * 101);

            // Display random number
            document.getElementById("randomNumberDisplay").textContent = "Random Number: " + randomNumber;
        });
    </script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotNetProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DotNetProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DotNetProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Index">Company</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RandomNumber" asp-action="Index">Random Number</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>